---
# Update package cache
- name: Update package cache
  package:
    update_cache: yes

- name: Install Python3 and pip
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install virtualenv using pip3
  pip:
    name: virtualenv
    executable: pip3


- name: Install Git
  package:
    name: git
    state: present






- name: Enable PostgreSQL module on Amazon Linux 2023
  ansible.builtin.command: "dnf module enable -y postgresql:{{ postgres_version }}"
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"


- name: Install PostgreSQL packages on Amazon Linux 2023
  dnf:
    name:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - postgresql-devel
    state: present
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"

# Install PostgreSQL (Amazon Linux 2 / RHEL / CentOS)
- name: Install PostgreSQL packages on Amazon Linux 2 / RHEL / CentOS
  yum:
    name:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - postgresql-devel
    state: present
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

# Initialize PostgreSQL database (Amazon Linux)
- name: Initialize PostgreSQL database (Amazon Linux)
  command: "/usr/bin/postgresql-setup --initdb"
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
  when: ansible_distribution == "Amazon"

# Ensure PostgreSQL service is running
- name: Ensure PostgreSQL is running and enabled
  service:
    name: postgresql
    state: started
    enabled: yes

