---
    - name: Update yum package cache
      yum:
        update_cache: yes

    - name: Install Python3 and pip
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install virtualenv
      pip:
        name: virtualenv
        executable: pip3

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install PostgreSQL on Amazon Linux
      yum:
        name:
          - postgresql
          - postgresql-server
          - postgresql-contrib
          - postgresql-devel
        state: present

    - name: Initialize PostgreSQL database (only on Amazon Linux 2)
      command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Ensure PostgreSQL service is started and enabled
      systemd:
        name: postgresql
        state: started
        enabled: yes    
...
