---
- name: Install Java (required for Jenkins)
  amazon-linux-extras:
    name: java-openjdk11
    state: present

- name: Add Jenkins repository
  template:
    src: jenkins.repo.j2
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins port 8080
  wait_for:
    port: 8080
    delay: 10
    timeout: 60

- name: Show initial Jenkins admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_initial_password
  ignore_errors: yes

- debug:
    msg: "Jenkins initial admin password: {{ jenkins_initial_password.stdout }}"

